### ISSUE TITLE
Issue about the event data from kitti-360 dataset

### ISSUE THREAD

**Issue by dianzizs** [jamycheung/DELIVER#2]
![image](https://user-images.githubusercontent.com/51194772/232747821-44b4c0ff-1cb6-4d23-bdf4-5c127b716d7a.png)

It seems that there are no subcategories for the event dataset on the official web page of the kitti-360 dataset, and a query of the paper revealed that the depth and event subcategories of the kitti dataset are generated from some off-the-shelf models.

Will you publish the event and depth versions of kitti? If not, can I ask for the detailed steps of the dataset making?

**Comment by jamycheung** [comment]
Hi, thanks for your interest.
For now, we have no plan to publish the generated event and depth from KITTI-360, because we will basically focus on the DELIVER dataset that has original event and depth information. 
If you have interest, I suggest to generate event by using [ESIM](https://github.com/uzh-rpg/rpg_esim), and depth by using [AANet](https://github.com/haofeixu/aanet). We follow the defaul settings from their repositories. Please let me know if you have further question.
